@doc "Red circle"
const RC = "🔴"
@doc "Green circle"
const GC = "🟢"
@doc "Yellow circle"
const YC = "🟡"
@doc "Blue circle"
const BC = "🔵"
@doc "Black circle"
const KC = "⚫"
@doc "Down arrow"
const DA = "⬇"
@doc "Up arrow"
const UA = "⬆"
@doc "Left-right arrow"
const LRA = "↔"
